export const jobs = [
  {
    id: 1,
    icon: "fa-solid fa-code",
    jobType: "Full-Time",
    companyName: "Revolut",
    jobTitle: "Email Marketing",
    location: "Madrid, Spain",
    category: "Marketing",
    description: "Revolut is looking for Email Marketing to help team manage their email marketing campaigns.",
    keywords: ["Marketing", "Design"],
  },
  {
    id: 2,
    icon: "fa-solid fa-code",
    jobType: "Full-Time",
    jobTitle: "Brand Designer",
    companyName: "Dropbox",
    location: "San Fransisco, US",
    category: "Design",
    description: "Dropbox is looking for Brand Designer to help the team to design new features",
    keywords: ["Design", "Business"],
  },
  {
    id: 3,
    icon: "fa-solid fa-code",
    jobType: "Part-Time",
    jobTitle: "Email Marketing",
    companyName: "Pitch",
    location: "Berlin, Germany",
    category: "Marketing",
    description: "Pitch is looking for Customer Manager to join marketing team",
    keywords: ["Marketing"],
  },
  {
    id: 4,
    icon: "fa-solid fa-code",
    jobType: "Full-Time",
    jobTitle: "Visual Designer",
    companyName: "Blinkist",
    location: "Granada, Spain",
    category: "Design",
    description: "Blinkist is looking for Visual Designer to help team design new features",
    keywords: ["Design"],
  },
  {
    id: 5,
    icon: "fa-solid fa-code",
    jobType: "Full-Time",
    jobTitle: "Product Designer",
    companyName: "ClassPass",
    location: "Manchaster, UK",
    category: "Design",
    description: "ClassPass is looking for Product Designer to help us design new features",
    keywords: ["Marketing", "Design"],
  },
  {
    id: 6,
    icon: "fa-solid fa-code",
    jobType: "Full-Time",
    jobTitle: "Lead Designer",
    companyName: "Canva",
    location: "Ontario, Canada",
    category: "Engineering",
    description: "Canva is looking for Lead Engineer to help develop new features",
    keywords: ["Design"],
  },
  {
    id: 7,
    icon: "fa-solid fa-code",
    jobType: "Full-Time",
    jobTitle: "Brand Strategist",
    companyName: "GoDaddy",
    location: "Marselle, France",
    category: "Marketing",
    description: "GoDaddy is looking for Brand Strategist to join their team",
    keywords: ["Marketing"],
  },
  {
    id: 8,
    icon: "fa-solid fa-code",
    jobType: "Full-Time",
    jobTitle: "Data Analyst",
    companyName: "Twitter",
    location: "San Diego, US",
    category: "Technology",
    description: "Twitter is looking for Data Analyst to help team desing their product.",
    keywords: ["Technology"],
  },
];

export async function GET(request) {
  return Response.json({
    success: true,
    status: 200,
    message: "Hello from API",
  })
}