import { Epilogue } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const epilogue = Epilogue({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${epilogue.className} antialiased`}
      >
        <header>
          <Navbar />
        </header>
        <main>

          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
